<a href="https://colab.research.google.com/github/anuragpatil811/Applied-Data-Analysis/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

In [22]:
data1 = {
    "Name": ["Anurag", "Ritesh", "Abhishek", None, "Neha"],
    "Age": [25, None, 22, 28, 26],
    "Salary": [50000, 60000, None, 70000, 45000]
}

In [23]:
df1 = pd.DataFrame(data1)

In [24]:

df.isnull().sum()

ID      0
Name    0
City    0
dtype: int64

In [27]:
df1["Age"].fillna(df1["Age"].mean(), inplace=True)
df1["Salary"].fillna(df1["Salary"].mean(), inplace=True)

/tmp/ipykernel_2729/2984914537.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Age"].fillna(df1["Age"].mean(), inplace=True)
/tmp/ipykernel_2729/2984914537.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Salary"].fillna(df1["Salary"].mean(), inplace=True)

In [28]:
data2 = {
    "ID": [101, 102, 103, 101, 104],
    "Name": ["Amit", "Priya", "Rahul", "Amit", "Neha"],
    "City": ["Delhi", "Mumbai", "Chennai", "Delhi", "kolkata"]
}

In [29]:
df2 = pd.DataFrame(data2)

In [30]:
df2.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [31]:
df2.drop_duplicates(inplace=True)

In [33]:
df2.dtypes

ID       int64
Name    object
City    object
dtype: object

In [34]:
df1["Age"] = pd.to_numeric(df1["Age"], errors="coerce")

In [35]:
import numpy as np
salary_data = pd.DataFrame({"Salary": [50000, 55000, 60000, 1000000,
65000]})

In [36]:
mean = np.mean(salary_data["Salary"])
std_dev = np.std(salary_data["Salary"])

In [37]:
outlier_threshold = mean + 3*std_dev

In [38]:
cleaned_salary = salary_data[salary_data["Salary"]<outlier_threshold]
cleaned_salary

    Salary
0    50000
1    55000
2    60000
3  1000000
4    65000

In [39]:
df3 = pd.DataFrame({"City": ["mumbai", "Mumbai", "MUMBAI", "Delhi", "delhi"]})
df3["City"] = df3["City"].str.lower()
print(df3)

     City
0  mumbai
1  mumbai
2  mumbai
3   delhi
4   delhi