In [1]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\Python\Pandas\Military Expenditure.csv")

In [3]:
df.head()

,Name,Code,Type,Indicator Name,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,Country,Military expenditure (current USD),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Country,Military expenditure (current USD),NaN,NaN,NaN,NaN,NaN,NaN,...,2.518695e+08,2.981469e+08,3.258070e+08,2.385834e+08,2.171941e+08,2.682271e+08,1.995186e+08,1.858783e+08,1.914071e+08,1.980863e+08
2,Angola,AGO,Country,Military expenditure (current USD),NaN,NaN,NaN,NaN,NaN,NaN,...,3.311193e+09,3.500795e+09,3.639496e+09,4.144635e+09,6.090752e+09,6.841864e+09,3.608299e+09,2.764055e+09,3.062873e+09,1.983614e+09
3,Albania,ALB,Country,Military expenditure (current USD),NaN,NaN,NaN,NaN,NaN,NaN,...,1.827369e+08,1.858932e+08,1.970068e+08,1.832047e+08,1.800155e+08,1.781204e+08,1.323507e+08,1.308532e+08,1.443827e+08,1.804887e+08
4,Andorra,AND,Country,Military expenditure (current USD),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.dropna(inplace=True)

In [5]:
df.head()

,Name,Code,Type,Indicator Name,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
11,Australia,AUS,Country,Military expenditure (current USD),4.597601e+08,4.709601e+08,4.894401e+08,5.532801e+08,6.557601e+08,7.873601e+08,...,1.896014e+10,2.321769e+10,2.659720e+10,2.621658e+10,2.482526e+10,2.578371e+10,2.404557e+10,2.638295e+10,2.769111e+10,2.671183e+10
12,Austria,AUT,Country,Military expenditure (current USD),9.155910e+07,9.102985e+07,1.000270e+08,1.259599e+08,1.645947e+08,1.428957e+08,...,3.334755e+09,3.218351e+09,3.409721e+09,3.187227e+09,3.229066e+09,3.305159e+09,2.665410e+09,2.885947e+09,3.138359e+09,3.367460e+09
15,Belgium,BEL,Country,Military expenditure (current USD),3.832202e+08,3.912188e+08,4.222208e+08,4.446013e+08,4.970592e+08,5.007221e+08,...,5.620670e+09,5.244721e+09,5.499371e+09,5.168998e+09,5.263165e+09,5.191509e+09,4.202063e+09,4.314102e+09,4.484653e+09,4.959692e+09
17,Burkina Faso,BFA,Country,Military expenditure (current USD),1.268378e+06,1.643154e+06,4.901761e+06,5.281288e+06,5.358593e+06,3.509330e+06,...,1.273333e+08,1.237005e+08,1.388509e+08,1.477297e+08,1.661363e+08,1.771670e+08,1.479347e+08,1.494674e+08,1.910658e+08,3.124676e+08
27,Brazil,BRA,Country,Military expenditure (current USD),3.827298e+08,3.423397e+08,3.874490e+08,4.419996e+08,3.542279e+08,6.328690e+08,...,2.564881e+10,3.400294e+10,3.693621e+10,3.398701e+10,3.287479e+10,3.265961e+10,2.461770e+10,2.422475e+10,2.928305e+10,2.776643e+10

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 66 entries, 11 to 261
Data columns (total 63 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            66 non-null     str
 1   Code            66 non-null     str
 2   Type            66 non-null     str
 3   Indicator Name  66 non-null     str
 4   1960            66 non-null     float64
 5   1961            66 non-null     float64
 6   1962            66 non-null     float64
 7   1963            66 non-null     float64
 8   1964            66 non-null     float64
 9   1965            66 non-null     float64
 10  1966            66 non-null     float64
 11  1967            66 non-null     float64
 12  1968            66 non-null     float64
 13  1969            66 non-null     float64
 14  1970            66 non-null     float64
 15  1971            66 non-null     float64
 16  1972            66 non-null     float64
 17  1973            66 non-null     float64
 18  1974            66 non-null     float64
 19  1975            66 non-null     float64
 20  1976            66 non-null     float64
 21  1977            66 non-null     float64
 22  1978            66 non-null     float64
 23  1979            66 non-null     float64
 24  1980            66 non-null     float64
 25  1981            66 non-null     float64
 26  1982            66 non-null     float64
 27  1983            66 non-null     float64
 28  1984            66 non-null     float64
 29  1985            66 non-null     float64
 30  1986            66 non-null     float64
 31  1987            66 non-null     float64
 32  1988            66 non-null     float64
 33  1989            66 non-null     float64
 34  1990            66 non-null     float64
 35  1991            66 non-null     float64
 36  1992            66 non-null     float64
 37  1993            66 non-null     float64
 38  1994            66 non-null     float64
 39  1995            66 non-null     float64
 40  1996            66 non-null     float64
 41  1997            66 non-null     float64
 42  1998            66 non-null     float64
 43  1999            66 non-null     float64
 44  2000            66 non-null     float64
 45  2001            66 non-null     float64
 46  2002            66 non-null     float64
 47  2003            66 non-null     float64
 48  2004            66 non-null     float64
 49  2005            66 non-null     float64
 50  2006            66 non-null     float64
 51  2007            66 non-null     float64
 52  2008            66 non-null     float64
 53  2009            66 non-null     float64
 54  2010            66 non-null     float64
 55  2011            66 non-null     float64
 56  2012            66 non-null     float64
 57  2013            66 non-null     float64
 58  2014            66 non-null     float64
 59  2015            66 non-null     float64
 60  2016            66 non-null     float64
 61  2017            66 non-null     float64
 62  2018            66 non-null     float64
dtypes: float64(59), str(4)
memory usage: 36.9 KB

In [8]:
df2 = df[df["Year"] > 2000]
df2.head()

KeyError: 'Year'