<a href="https://colab.research.google.com/github/anuragpatil811/Applied-Data-Analysis/blob/main/Pivot_Tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "Region": ["North", "South", "East", "West", "North", "South"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [15000, 18000, 12000, 25000, 17000, 22000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
pivot_table = df.pivot_table(values="Sales",index="Region", columns="Product", aggfunc="sum")

In [5]:
pivot_table

Product        A        B
Region
East     12000.0      NaN
North    32000.0      NaN
South        NaN  40000.0
West         NaN  25000.0

In [6]:
pivot_table = df.pivot_table(values="Sales", index="Region", aggfunc=["sum", "mean", "count"])
pivot_table

          sum     mean count
        Sales    Sales Sales
Region
East    12000  12000.0     1
North   32000  16000.0     2
South   40000  20000.0     2
West    25000  25000.0     1